폐암 수술 환자 생존율 예측. 데이터 출처: 폴란드 브로츠와프 의과대학 

In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split

In [3]:
import numpy as np
import tensorflow as tf

In [4]:
seed=0
np.random.seed(3)
tf.random.set_seed(3)

In [5]:
print(np.random.seed(3))
print(tf.random.set_seed(3))

None
None


In [6]:
Data_set=np.loadtxt("D:\\ai\\Software Practical Use and Coding\\12\\ThoraricSurgery.csv", delimiter=",")

In [7]:
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [9]:
X = Data_set[:,0:17]
Y = Data_set[:,17]

In [10]:
# 학습 데이터 70 %, 테스트 데이터셋 30% 로 설정
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)

In [11]:
X_train

array([[434.  ,   3.  ,   4.28, ...,   1.  ,   0.  ,  66.  ],
       [396.  ,   4.  ,   3.04, ...,   1.  ,   0.  ,  64.  ],
       [ 26.  ,   5.  ,   4.56, ...,   1.  ,   0.  ,  57.  ],
       ...,
       [ 85.  ,   3.  ,   4.28, ...,   1.  ,   0.  ,  51.  ],
       [419.  ,   2.  ,   2.6 , ...,   0.  ,   0.  ,  70.  ],
       [161.  ,   3.  ,   2.92, ...,   0.  ,   0.  ,  76.  ]])

In [12]:
len(X_train)

329

In [13]:
X_test

array([[344.  ,   3.  ,   2.96, ...,   1.  ,   0.  ,  60.  ],
       [238.  ,   3.  ,   3.24, ...,   1.  ,   0.  ,  69.  ],
       [172.  ,   2.  ,   2.88, ...,   1.  ,   0.  ,  62.  ],
       ...,
       [ 40.  ,   3.  ,   4.6 , ...,   1.  ,   0.  ,  52.  ],
       [456.  ,   4.  ,   2.92, ...,   1.  ,   0.  ,  70.  ],
       [355.  ,   3.  ,   4.28, ...,   1.  ,   0.  ,  60.  ]])

In [14]:
len(X_test)

141

In [15]:
Y_train

array([0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0.

In [16]:
len(Y_train)

329

In [17]:
Y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0.])

In [18]:
len(Y_test)

141

In [19]:
model = Sequential()
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [20]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=100, batch_size=10) # 학습 데이터셋 329 개로 학습

Train on 329 samples
Epoch 1/100
329/329 [==============================] - 1s 2ms/sample - loss: 0.9772 - accuracy: 0.7447
Epoch 2/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4976 - accuracy: 0.8359
Epoch 3/100
329/329 [==============================] - 0s 70us/sample - loss: 0.4779 - accuracy: 0.8359
Epoch 4/100
329/329 [==============================] - 0s 70us/sample - loss: 0.4743 - accuracy: 0.8116
Epoch 5/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4826 - accuracy: 0.8328
Epoch 6/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4546 - accuracy: 0.8359
Epoch 7/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4638 - accuracy: 0.8359
Epoch 8/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4579 - accuracy: 0.8298
Epoch 9/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4447 - accuracy: 0.8298
Epoch 10/100
329/329 [======================

329/329 [==============================] - 0s 73us/sample - loss: 0.4341 - accuracy: 0.8389
Epoch 79/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4025 - accuracy: 0.8450
Epoch 80/100
329/329 [==============================] - 0s 70us/sample - loss: 0.4420 - accuracy: 0.8176
Epoch 81/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4143 - accuracy: 0.8511
Epoch 82/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4105 - accuracy: 0.8480
Epoch 83/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4194 - accuracy: 0.8389
Epoch 84/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4101 - accuracy: 0.8419
Epoch 85/100
329/329 [==============================] - 0s 70us/sample - loss: 0.4155 - accuracy: 0.8450
Epoch 86/100
329/329 [==============================] - 0s 73us/sample - loss: 0.4501 - accuracy: 0.8146
Epoch 87/100
329/329 [==============================] - 0s 73us/samp

In [21]:
# 30%에 해당하는 141개의 테스트 데이터셋으로 정확도 계산 결과를 출력

print("\n Test Accuracy : %.4f" % (model.evaluate(X_test, Y_test)[1]))  #테스트 데이터셋 141 개로 정확도 계산 

141/1 [=================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

딥러닝 학습모델을 이용한 테스트. <br>
predict- 테스트 데이터를 이용한 성능평가-> 학습에 활용안한 테스트 데이터셋 쓰는게<br> 바람직할것

In [22]:
import numpy as np
kim = np.array([[293,1,3.8,2.8,0,0,0,0,0,0,12,0,0,0,1,0,62]])
print(model.predict(kim))

test_kim  = model.predict(kim)*100
print("백분율로 표시 : ",test_kim) 
print("Kim 폐암 수술 후 생존율 예측 : %.2f" %test_kim, "%")

[[0.03467145]]
백분율로 표시 :  [[3.4671447]]
Kim 폐암 수술 후 생존율 예측 : 3.47 %


In [23]:
park = np.array([[197,3,2.84,2.24,1,1,1,0,0,0,12,0,0,0,1,0,68]])
print(model.predict(park))


park_predict = model.predict(park)*100
print("백분율로 표시 : ",park_predict) 
print("park 폐암 수술 후 생존율 예측 : %.2f" %park_predict, "%")

[[0.10510612]]
백분율로 표시 :  [[10.5106125]]
park 폐암 수술 후 생존율 예측 : 10.51 %


In [ ]:
#h5 파일로 젖